#!/usr/bin/env bash
# Write a bash script Process and PID File
# Creates, Displays an Delete
# Receiving a SIGQUIT or SIGTERM signal

function love() {
    rm /var/run/myscrip.pid
    exit
}

trap 'echo "I hate the kill command";love' SIGTERM
trap 'echo "Y U no love me?!";love' SIGINT

echo $$ >> /var/run/myscript.pid
while true; do
    echo "To infinity and beyond";
done
