#!/usr/bin/env bash
# Sript display to infinity and beyond indefinitely
# with sleep 2 in between

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "To infinity and beyond"
    sleep 2
done
